version: "3.5"

networks:
  esphome:
  esphome-private:

volumes:
  esphome:
  esphome-db:

#secrets:
  # Secrets format
  # ${service_name}_${mount_point}:
  #   name: ${STACK_NAME:-technocore}_${service_name}_${mount_point}
  # #   external: true
  esphome_admin_username:
    name: ${STACK_NAME:-technocore}_esphome_admin_username
    external: true
  esphome_admin_password:
    name: ${STACK_NAME:-technocore}_esphome_admin_password
    external: true
  esphome_esphome-db_username:
    name: ${STACK_NAME:-technocore}_esphome_esphome-db_username
    external: true
  esphome_esphome-db_password:
    name: ${STACK_NAME:-technocore}_esphome_esphome-db_password
    external: true

services:
  ## Uncomment this if Traefik will be used for routing traffick to this service.
  #ingress:
  #  networks:
  #    - esphome

  esphome:
    deploy:
      labels:
      #  # These env vars should infact be uppercase
      #  - traefik.frontend.rule=$ESPHOME_ROUTING_LABEL
      #  - traefik.frontend.priority=$ESPHOME_ROUTING_LABEL_PRIORITY
      #  - traefik.port=SET_ME_PLEASE
      #  - ${TRAEFIK_BASIC_AUTH}
      #  - traefik.enable=true
      #  # You'll need to set applicaiton's port here.
      #  - traefik.tags=ingress 
      #  - traefik.docker.network=${STACK_NAME:-technocore}_esphome
      #  # Traefik service that listens to HTTP
      #  - traefik.redirectorservice.frontend.entryPoints=http
      #  - traefik.redirectorservice.frontend.redirect.entryPoint=https
      #  # Traefik service that listens to HTTPS
      #  - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    #environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
    image: ${image_provider:-scififarms}/technocore-esphome:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - esphome
      - esphome-private
    #secrets:
    #  - source: esphome_esphome_db_username
    #    target: esphome_db_username
    #  - source: esphome_esphome_db_password
    #    target: esphome_db_password
    #  - source: esphome_domain
    #    target: domain
    volumes:
      # Likely need to change this
      - esphome:/var/lib/esphome

  esphome_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    #environment:
    image: ${image_provider:-scififarms}/technocore-esphome-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - esphome-private
    secrets:
      - source: esphome_db_admin_username
        target: admin_username
      - source: esphome_db_admin_password
        target: admin_password
      - source: esphome_db_esphome_username
        target: esphome_username
      - source: esphome_db_esphome_password
        target: esphome_password
    volumes:
      # Likely need to change this
      - esphome-db:/var/lib/esphome
